create table client (numero bigint generated by default as identity, nom varchar(255), prenom varchar(255), primary key (numero));
create table client_compte (num_client bigint not null, num_compte bigint not null);
create table compte (numero bigint generated by default as identity, label varchar(255), solde double, primary key (numero));
create table devise (code varchar(255) not null, echange double, nom varchar(255), primary key (code));
create table operation (num_op bigint generated by default as identity, date_op date, label varchar(255), montant double, num_compte bigint, primary key (num_op));
alter table client_compte add constraint FKggnv04cd9uupmyr9mxi22c9an foreign key (num_compte) references compte;
alter table client_compte add constraint FKgf8yv8smckpywht4afmpa43ip foreign key (num_client) references client;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte;
